name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to the latest version compatible with Node.js 20

    - name: Set up JDK 17
      uses: actions/setup-java@v4  # Updated to the latest version compatible with Node.js 20
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests
      run: mvn test
